#! /usr/bin/env bash
set -e
[ -n "$TMUXIFIER_DEBUG" ] && set -x

# Load internal utility functions.
source "$TMUXIFIER/lib/util.sh"

# Provide tmuxifier help
if calling-help "$@"; then
  echo "usage: tmuxifier new-session <layout_name>

Aliases: new-ses, nses, ns

Create a new session layout and open it for editing in \$EDITOR."
  exit
fi

# Provide tmuxifier completions
if calling-complete "$@"; then
  tmuxifier-list-sessions
  exit
fi

if [ -z "$1" ]; then
  echo "$(tmuxifier-help new-session $@)" >&2
  exit 1
fi

session_root="$2"
layout_name="$1"
layout_file="$TMUXIFIER_LAYOUT_PATH/${layout_name}.session.sh"
template="$TMUXIFIER/templates/session.sh"

if [ ! -f "$template" ]; then
  echo "tmuxifier: session layout template not found: $template" >&2
  exit 1
fi

if [ -f "$layout_file" ]; then
  echo "session layout '$layout_name' already exists." >&2
  echo "" >&2
  echo "You can edit it with:" >&2
  echo "  tmuxifier edit-session \"$layout_name\"" >&2
  exit 1
fi


template_content=$(cat "$template")
layout_name_regex="{{SESSION_NAME}}"
session_root_regex="{{SESSION_ROOT}}"

template_content=${template_content//$layout_name_regex/$layout_name}
template_content=${template_content//$session_root_regex/$session_root}

echo "$template_content" > "$layout_file"


if [ -n "$EDITOR" ]; then
  exec $EDITOR "$layout_file"
else
  echo "Layout file has been created, but '\$EDITOR' is not set. Please "
  echo "manually open the layout for editing:"
  echo "$layout_file"
  echo
fi
