#! /usr/bin/env bash
DEFAULT_SESSION_NAME="qq"
proj_root_dir="$HOME/code"

get_session_root() {
path=$1
while true; do
    if [[ $(dirname $path) = $proj_root_dir ]]; then
      break
    elif [[ -e "$path/.git" ]]; then
      break
    elif [[ $path = $HOME ]]; then
      break
    else
      path=${path%/*}
    fi
  done
  echo "$path"
}

get_session_name() {
  [[ ! -z "$1" && "$1" != $HOME ]] && echo $(basename $1) || echo $DEFAULT_SESSION_NAME
}
load_session_layout() {
  is_check=$1
  if [[ $is_check == 1 ]]; then
    read -n1 -r -p "Session layout for $session_name already exists. Press 'e' to edit or any key to load" key
    [[ "$key" = 'e' ]] && tmuxifier edit-session "$session_name"
  fi
  tmuxifier load-session "$session_name"
}

session_root=$(get_session_root $(find $HOME | fzf))
session_name=$(get_session_name $session_root)
layout_file="$TMUXIFIER_LAYOUT_PATH/$session_name.session.sh"

if [[ ! -f "$layout_file" ]]; then
  tmuxifier new-session $session_name $session_root
  load_session_layout 0
else
  load_session_layout 1
fi
